# Generated by Django 4.0.4 on 2022-06-06 22:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_article_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imageURL'),
        ),
    ]
